### ISSUE TITLE
demo跑起来之后，菜单栏点击没有反应

### ISSUE THREAD

**Issue by captianli** [ambit-tsai/reactie#7]
demo跑起来之后，菜单栏点击没有反应：不知道是什么原因
![image](https://user-images.githubusercontent.com/37542643/53957017-3bcfb780-4118-11e9-979d-45b480015a0a.png)

**Comment by captianli** [comment]
解决了，引入的Router貌似有点问题，注释掉了下面这句：

![image](https://user-images.githubusercontent.com/37542643/53961572-e0a3c200-4123-11e9-80b3-3ed9f85e1fa9.png)

**Comment by harrydengchao** [comment]
按如上注释掉，也未能解决。 这个 `onClick` 事件根本就没触发...，这如何搞

**Comment by harrydengchao** [comment]
很神奇啊，我把项目和浏览器都关了后，过了会儿再起，又可以了...
